GET http://localhost:8080/posts


###

GET http://localhost:8080/posts/1

###

POST http://localhost:8080/posts
Content-Type: application/json

{
  "titulo": "jorjao@d.w",
  "texto": "boyzo",
  "userId": 1
}
